# Generated by Django 4.2.1 on 2023-06-12 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0002_city_uid'),
    ]

    operations = [
        migrations.CreateModel(
            name='Alert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city_names', models.CharField(max_length=30)),
                ('alert_name', models.CharField(choices=[(0, 'TEMP_RISE'), (1, 'THUNDERSTORM'), (2, 'RANING')], max_length=1)),
                ('condition', models.CharField(choices=[(0, 'GT'), (1, 'LT'), (2, 'LTQ'), (3, 'GTQ'), (4, 'EQ')], max_length=1)),
                ('threshold', models.IntegerField()),
            ],
        ),
        migrations.RemoveField(
            model_name='city',
            name='uid',
        ),
        migrations.AlterField(
            model_name='city',
            name='name',
            field=models.CharField(default='', max_length=25),
        ),
    ]
