# Generated by Django 4.2.1 on 2023-06-13 05:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0003_alert_remove_city_uid_alter_city_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alert',
            name='alert_name',
            field=models.CharField(choices=[('TEMP_RISE', 'Temperature Rise'), ('RANING', 'Raining'), ('THUNDERSTORM', 'Thunderstorm')], max_length=50),
        ),
        migrations.AlterField(
            model_name='alert',
            name='city_names',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='weather.city'),
        ),
        migrations.AlterField(
            model_name='alert',
            name='condition',
            field=models.CharField(choices=[('GT', 'Greater Than'), ('LT', 'Less Than')], max_length=10),
        ),
        migrations.AlterField(
            model_name='alert',
            name='threshold',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
    ]
